### ISSUE TITLE
Feature  Request: ARM binary for ARM devices

### ISSUE THREAD

**Issue by Juli199696** [M-HT/SR#11]
Please add support for ARM devices such as the raspberry pi. Would be awesome to play on that little thing.

**Comment by M-HT** [comment]
ARM devices are supported from the beginning of the project. The original goal of the project was to play the games on ARM devices (first [GP2X](https://en.wikipedia.org/wiki/GP2X) and later [Pandora](https://en.wikipedia.org/wiki/Pandora_(console))). The games can be compiled and played on Raspberry Pi.

**Comment by Juli199696** [comment]
How do i compile these? Im not that advanced please help me.

**Comment by M-HT** [comment]
You didn't specify much, so let's assume you want to compile Albion and you have Raspberry Pi 2 or newer model. Everything will be done on Raspberry Pi.

Install packages with command `sudo apt install build-essential git scons`
The game can either use SDL1.2 with OpenGL or SDL2.
If using SDL1.2 then install these packages `sudo apt install libsdl1.2-dev libsdl-mixer1.2-dev`
If using SDL2 then install these packages `sudo apt install libsdl2-dev libsdl2-mixer-dev`
Other packages might be needed, but I don't have a fresh install to test it.

Download the source, for instance using command `git clone https://github.com/M-HT/SR.git`

In directory SR/SR/udis86-1.6 run these commands:
`./configure`
`make`

In file SR/SR/SR_defs.h change line:
`#define OUTPUT_TYPE  OUT_X86`
to:
`#define OUTPUT_TYPE  OUT_ARM_LINUX`

In directory SR/SR run command `scons`

Copy file SR/SR/SR.exe to directory SR/SR-games/Albion/SR
Copy file MAIN.EXE (from Albion) to directory SR/SR-games/Albion/SR

In directory SR/SR-games/Albion/SR run command `./build-arm.sh`

From directory SR/SR-games/Albion/SR copy files Albion-main.s, seg01.inc, ..., seg09.inc to directory SR/games/Albion/SR-Main/arm

In directory SR/games/Albion/SR-Main run command `scons` when using SDL1.2 or when using SDL2 then run command `scons sdl2=1`

Copy file SR/games/Albion/SR-Main/SR-Main to Albion directory.
Copy file SR/pycfg/pycfg.py to Albion directory.
Copy all files from SR/games/Albion/release/linux to Albion directory.

Read readme-Linux.txt on how to setup the game.

This should allow you to play Albion without music, but I'll explain how to compile music libraries when you compile the base executable. Ask questions if you don't understand anything or if some errors occur.

**Comment by Juli199696** [comment]
Oh im so sorry, i was so deep into testing yesterday that i forgot to mention what kind of game and system i want to use.

Ofc. Raspberry Pi 4 and the game Septerra Core.

**Comment by M-HT** [comment]
I had to fix some bugs, but here's how you compile Septerra Core on Raspberry Pi.

Install packages with command `sudo apt install build-essential git scons automake gdc llvm libsdl2-dev libmpg123-dev libquicktime-dev`

Get the latest sources, for instance using command `git clone https://github.com/M-HT/SR.git`

In directory SR/SRW/udis86-1.7.2 run these commands:
`aclocal`
`automake`
`./configure`
`make`

In file SR/SRW/SR_defs.h change line:
`#define OUTPUT_TYPE  OUT_X86`
to:
`#define OUTPUT_TYPE  OUT_LLASM`

In directory SR/SRW run command `scons`

Copy file SR/SRW/SRW.exe to directory SR/SRW-games/Septerra Core/SRW
Copy file Septerra104.exe (from Septerra Core) to directory SR/SRW-games/Septerra Core/SRW
Or if it doesn't exist copy file septerra.exe (version 1.04 from Septerra Core) to directory SR/SRW-games/Septerra Core/SRW and rename it to Septerra104.exe

In directory SR/SRW-games/Septerra Core/SRW run command `./build-llasm.sh`

From directory SR/SRW-games/Septerra Core/SRW copy files Septerra.llasm, seg*.llinc to directory SR/games/Septerra Core/SR-Septerra/llasm

In directory SR/llasm run command `./komp.sh`

In directory SR/games/Septerra Core/SR-Septerra run command `PATH=$PATH:../../../llasm scons`

Copy file SR/games/Septerra Core/SR-Septerra/SR-Septerra to Septerra Core directory.
Copy all files from SR/games/Septerra Core/release/linux to Septerra Core directory.

Run the command `./Septerra.sh` in Septerra Core directory to play the game.

**Comment by Juli199696** [comment]
I get the following error when i try to run scons

pi@raspberrypi:~/Desktop/SR/SRW $ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o SRW_loader.o -c -O2 -Wall -I./udis86-1.7.2/. SRW_loader.c
In file included from SRW_loader.c:28:
SR_defs.h:29:10: fatal error: Judy.h: No such file or directory
 #include <Judy.h>
          ^~~~~~~~
compilation terminated.
scons: *** [SRW_loader.o] Error 1
scons: building terminated because of errors.

**Comment by M-HT** [comment]
Install package libjudy-dev with command `sudo apt install libjudy-dev`

**Comment by Juli199696** [comment]
Do you guys have a discord or something?

**Comment by M-HT** [comment]
No. And there's only me - no other people :smile:

**Comment by Juli199696** [comment]
Stack dump:
0.	Program arguments: llc -O=3 -filetype=obj 
1.	Running pass 'Function Pass Manager' on module '<stdin>'.
2.	Running pass 'ARM Instruction Selection' on function '@loc_4012E2'
Segmentation fault
scons: *** [llasm/Septerra.o] Error 139
scons: building terminated because of errors.

**Comment by M-HT** [comment]
Can you give me the output of the command `opt --version` ?
And also the output of the command `cat /etc/os-release` ?
If that doesn't work - what distribution are you running on your Raspberry Pi ?

**Comment by Juli199696** [comment]
LLVM (http://llvm.org/):
  LLVM version 7.0.1
  
  Optimized build.
  Default target: armv6k-unknown-linux-gnueabihf
  Host CPU: cortex-a72



---------------------------------------
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

-------------------------------
Im using latest Raspbian Buster.

**Comment by Juli199696** [comment]
maybe im missing some libs or something

**Comment by M-HT** [comment]
It looks like a bug in this version of LLVM. So let's use version 8.0.1 from LLVM website.

Download it with command `wget https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/clang+llvm-8.0.1-armv7a-linux-gnueabihf.tar.xz`

Unpack it with command `tar xvJf clang+llvm-8.0.1-armv7a-linux-gnueabihf.tar.xz`

In directory SR/games/Septerra Core/SR-Septerra run command `PATH=XXX/clang+llvm-9.0.1-armv7a-linux-gnueabihf/bin:$PATH:../../../llasm scons` where `XXX` is the path where you downloaded and unpacked LLVM.

**Comment by Juli199696** [comment]
Yo man, you are a genuius! That worked perfectly. 👯 Thank you very much and have a nice day!
