### ISSUE TITLE
septerra core linux walkthrough

### ISSUE THREAD

**Issue by NeonLightning** [M-HT/SR#12]
i was wondering if it would be possible to put together a guide for building a arm and or linux build of septerra core.

**Comment by M-HT** [comment]
You can read #11 for a guide to build Septerra Core on Raspberry Pi. Building it on x86 linux is similar, but easier. You don't need to install gdc and llvm packages, you don't need to edit SR_defs.h, you don't need to build llasm tool, but you need 32-bit versions of -dev packages.
