### ISSUE TITLE
aclocal and automake update

### ISSUE THREAD

**Issue by NeonLightning** [M-HT/SR#13]
this is built for 1.13 and the newest ubuntu ones are 1.15.1 right now making the script fail to find the command

**Comment by M-HT** [comment]
After I fixed some bugs with python3, here's how you compile Septerra Core on Ubuntu 20.04.

Install packages with command ```sudo apt install build-essential git scons automake libjudy-dev python-is-python3 nasm gcc-multilib libsdl2-dev:i386 libmpg123-dev:i386 libquicktime-dev:i386```

Get the latest sources, for instance using command ```git clone https://github.com/M-HT/SR.git```

In directory SR/SRW/udis86-1.7.2 run these commands:
```aclocal```
```automake```
```./configure```
```make```

In directory SR/SRW run command ```scons```

Copy file SR/SRW/SRW.exe to directory SR/SRW-games/Septerra Core/SRW
Copy file Septerra104.exe (from Septerra Core) to directory SR/SRW-games/Septerra Core/SRW
Or if it doesn't exist copy file septerra.exe (version 1.04 from Septerra Core) to directory SR/SRW-games/Septerra Core/SRW and rename it to Septerra104.exe

In directory SR/SRW-games/Septerra Core/SRW run command ./build-x86.sh

From directory SR/SRW-games/Septerra Core/SRW copy files Septerra.asm, seg*.inc to directory SR/games/Septerra Core/SR-Septerra/x86

In directory SR/games/Septerra Core/SR-Septerra run command ```scons```

Copy file SR/games/Septerra Core/SR-Septerra/SR-Septerra to Septerra Core directory.
Copy all files from SR/games/Septerra Core/release/linux to Septerra Core directory.

Run the command ```./Septerra.sh``` in Septerra Core directory to play the game.

**Comment by NeonLightning** [comment]
i'm on peppermint and it's based on bionic. there is no python-is-python3 package. and a package i can't recall right now that was  needed for the i386 sdl couldn't be installed because it conflicted with the non i386 version.
but i did get to this point.(end goal is llasm version so i can cross compile for an arm device running linux but i'm trying to see if i can get the x86 version running first)
`/programs/SR/games/Septerra Core/SR-Septerra $ scons
scons: Reading SConscript files ...

You didn't set any target device (parameter 'device').
'pc-linux' will be used for compiling.

scons: done reading SConscript files.
scons: Building targets ...
nasm -felf32 -O1 -w+orphan-labels -w-number-overflow -ix86/ -o x86/Septerra.o x86/Septerra.asm
x86/seg01.inc:21962: error: parser: instruction expected
x86/seg01.inc:21963: warning: label alone on a line without a colon might be in error [-w+orphan-labels]
x86/seg01.inc:24563: error: parser: instruction expected
x86/seg01.inc:24566: error: parser: instruction expected
x86/seg01.inc:24567: error: symbol `tcall' redefined
x86/seg01.inc:24567: error: parser: instruction expected
x86/seg01.inc:24568: warning: label alone on a line without a colon might be in error [-w+orphan-labels]
x86/seg01.inc:24568: error: symbol `endp' redefined
x86/seg01.inc:24569: error: parser: instruction expected
x86/seg01.inc:41477: error: symbol `tcall' redefined
x86/seg01.inc:41477: error: parser: instruction expected
x86/seg01.inc:41478: warning: label alone on a line without a colon might be in error [-w+orphan-labels]
x86/seg01.inc:41478: error: symbol `endp' redefined
x86/seg01.inc:68769: error: symbol `tcall' redefined
x86/seg01.inc:68769: error: parser: instruction expected
x86/seg01.inc:68770: warning: label alone on a line without a colon might be in error [-w+orphan-labels]
x86/seg01.inc:68770: error: symbol `endp' redefined
x86/seg01.inc:68771: error: symbol `proc' redefined
x86/seg01.inc:68771: error: parser: instruction expected
x86/seg01.inc:68774: error: symbol `load' redefined
x86/seg01.inc:68774: error: parser: instruction expected
x86/seg01.inc:96161: error: symbol `tcall' redefined
x86/seg01.inc:96161: error: parser: instruction expected
x86/seg01.inc:96162: warning: label alone on a line without a colon might be in error [-w+orphan-labels]
x86/seg01.inc:96162: error: symbol `endp' redefined
x86/seg01.inc:96163: error: symbol `proc' redefined
x86/seg01.inc:96163: error: parser: instruction expected
x86/seg01.inc:96268: error: symbol `tcall' redefined
x86/seg01.inc:96268: error: parser: instruction expected
x86/seg01.inc:96269: warning: label alone on a line without a colon might be in error [-w+orphan-labels]
x86/seg01.inc:96269: error: symbol `endp' redefined
x86/seg01.inc:96270: error: symbol `proc' redefined
x86/seg01.inc:96270: error: parser: instruction expected
scons: *** [x86/Septerra.o] Error 1
scons: building terminated because of errors.
`

**Comment by M-HT** [comment]
It looks like you something went wrong with this step:
In directory SR/SRW-games/Septerra Core/SRW run command ```./build-x86.sh```

Because it looks like .sci files from llasm directory were used in x86 build.

Did you run the commands from the script separately instead of running the script ?

**Comment by NeonLightning** [comment]
odd i did the same things as last time but now it's mostly working. i'm just getting sdl errors now because i can't run the sdl version.

**Comment by M-HT** [comment]
Can you install package ```libsdl2-2.0-0:i386``` (runtime, not the dev) to run the game ?

**Comment by NeonLightning** [comment]
libsdl2-2.0-0:i386 is already the newest version (2.0.8+dfsg1-1ubuntu1.18.04.4).
but when i try and install the -dev i get
dpkg: dependency problems prevent configuration of libmirclient-dev:i386:
 libmirclient-dev:amd64 (0.31.1-0ubuntu1) breaks libmirclientcpp-dev and is installed.
  libmirclient-dev:i386 (0.31.1-0ubuntu1) provides libmirclientcpp-dev.

**Comment by M-HT** [comment]
Run command ```sudo ln -s libSDL2-2.0.so.0.8.0 /usr/lib/i386-linux-gnu/libSDL2.so``` - that should allow you to finish the compilation.

**Comment by NeonLightning** [comment]
had to rename the file that was there already for some reason. but yes it compiled and worked thank you :)
