### ISSUE TITLE
Septerra Core: Game Stutters on Windows 10 64-bit System

### ISSUE THREAD

**Issue by GoronMegaZord** [M-HT/SR#15]
Thank you so much for making this patch! This is the only thing that seems to work for me. Movies work fine, the game is mostly playable, etc. I say it's -mostly- playable because every 5 seconds or so, the game will stutter/hiccup. I have tried changing various compatibility settings to no avail. 

The strange thing is that I can run the game perfectly fine if I use dgVoodoo alongside the original septerra.exe. But then I can't see the movies when using this version. So I am just going to switch between original and SR exe's depending if I want to see movies or focus on game play.

If this is a worthy avenue of inquiry for the devs here, I can provide further details if needed.

Thanks,
-Goron

**Comment by M-HT** [comment]
I don't have any stutter/hiccup in Windows 10 (tested on 2 computers). Which version (number) of Windows 10 are you using? And what are your settings in Septerra.cfg ?

**Comment by GoronMegaZord** [comment]
Hey there,

OS: Windows 10 Home, Version 1903, OS Build 18362.959
Septerra.cfg:
# Intro settings
# --------------
#
# Intro_Play=yes/no - play intro movies ? - default value is yes

Intro_Play=yes


# Display settings
# ----------------
#
# Display_Mode=window/desktop/fullscreen - window with defined size / fullscreen at current resolution / fullscreen with defined resolution
# Display_VSync=on/off - enable/disable vsync - default value is off
# Display_Width=x - horizontal size - default value is 640
# Display_Height=y - vertical size - default value is 480
# Display_Resizable=yes/no - resizable window ? - default value is no
Display_Mode=desktop
Display_VSync=on
Display_Width=640
Display_Height=480
Display_Resizable=no


# Audio settings
# ----------------
#
# Audio_BufferSize=x - audio buffer size (in samples) - 0 = automatic - must be a power of 2 (e.g. 256, 512, 1024, 2048, 4096, 8192)
Audio_BufferSize = 0
================================

Also, I tried all the display settings and it doesn't matter which one I use. The game will stutter right away on the main menu and in game play.

**Comment by GoronMegaZord** [comment]
Figured I'd make a new post this time. I made a quick video demoing the issue: https://youtu.be/TbESpzLgRA4

**Comment by M-HT** [comment]
Does the game stutter when you set `Display_VSync=off` ?

**Comment by GoronMegaZord** [comment]
Sadly, yes. It still skips if I set vsync off. :(

**Comment by M-HT** [comment]
I tested it on a third computer, this one using version 1903 of Windows 10 and still no stuttering.
Try downloading latest SDL2 32-bit library (version [2.0.12](https://libsdl.org/release/SDL2-2.0.12-win32-x86.zip) currently) and replace SDL2.dll in Septerra Core directory with the downloaded one. That's my last idea of what to try.

**Comment by GoronMegaZord** [comment]
Will do! I'll give it a try tonight and let you know how it goes. 👍

**Comment by GoronMegaZord** [comment]
Hey again - I used the newer SDL as you suggested. The game still skips, albeit slightly less. It's most noticeable when holding the mouse button down to move and trying to change direction. Thank you for trying though. Appreciate it.

**Comment by Juli199696** [comment]
What Graphicscard do you use? Also check for Default Settings in the GPU Settings. I know that on the Nvidia Control Panel you can do some stuff that can lead to stutter in old games.

**Comment by Hlavoun** [comment]
Yeah, I had to disable gsync while playing Albion because of the stuttering. So gsync and freesync are better left disabled for these old "low fps" games.

**Comment by M-HT** [comment]
Is this still a problem in latest Septerra Core release (version 1.04.0.5) ?
And if yes, does it help if you use the option ```Display_DelayAfterFlip``` to lower the FPS ?

**Comment by M-HT** [comment]
Closing because of lack of response.

**Comment by Zombeaver** [comment]
I'm having this issue as well. Display_DelayAfterFlip does nothing. Vsync on or off does nothing. Disabling G-Sync does nothing. Manually forcing my monitor (which is normally 165hz) to 60hz does nothing.

As far as I can tell this is actually a DPI issue. My mouse is normally set to 1400 DPI and, at that value, normal mouse movement makes the cursor stutter like crazy. The lower I drop the DPI the less noticeable it becomes and at about 400 DPI if I don't move the mouse very quickly it goes away entirely. Messing with Windows' high DPI compatibility settings (set to "Application") doesn't seem to change anything.

**Comment by Zombeaver** [comment]
Correct, it's not like that. I thought the game itself was stuttering originally but it's not. It's just the cursor movement.

**Comment by M-HT** [comment]
@Zombeaver I posted a test executable in issue 30 - can you test whether it fixes the problem with high polling rate or not ?
