### ISSUE TITLE
Question: How to get music playing in Albion?

### ISSUE THREAD

**Issue by jtrees** [M-HT/SR#19]
I have compiled the wildmidi plugins and put both `midi-wildmidi.so` and `midiA-wildmidi.so` in the same directory as the `SR-Main` executable. I have also set `Audio_MIDI_Subsystem=wildmidi` in `Albion.cfg`.

When I execute the game I get sound effects but no music. What am I missing?

**Comment by M-HT** [comment]
Music is described in [midi-plugins](https://github.com/M-HT/SR/blob/master/midi-plugins/README.md) and in [readme](https://github.com/M-HT/SR/blob/master/games/Albion/release/linux/readme-Linux.txt) (Music section).

In case of WildMIDI, you're missing GUS patches. Quoting from the readme:
`GUS patches can be installed anywhere, but the file timidity.cfg must be either in the game's directory or in /etc/timidity/timidity.cfg`
`EawPats is a good sounding set of patches.`
