### ISSUE TITLE
allow HQ scaling (or any similar scaler)

### ISSUE THREAD

**Issue by FyiurAmron** [M-HT/SR#21]
I understand that many people favour the original pixelated look, but since HQ scalers has been around for a long time, I think it's reasonable to allow player to choose the scaler himself, instead of being forced to use simple pixel scaling.

(https://sourceforge.net/projects/xbrz/ comes to mind here, since it provides a really great visual experience w.r.t. old low-res games)

Scalers might be implemented directly via SR, or via proxy DLL similar to https://www.syntax-k.de/projekte/sdl-opengl-hq/ IMHO.

Alternatively, allow running the game with the base resolution (360x240) with just the bitdepth flip(8->32), so that one can benefit from SDL proxy scalers. (currently impossible to do, since the minimum resolution is 640x480, and the scalers provide little effect on already upscaled gfx)

**Comment by Dwedit** [comment]
I had developed a tool called GameStretcher that hooks GDI, DirectDraw, and Direct3D9, and uses a SuperXBR shader.
https://github.com/Dwedit/GameStretcher

But if the program is doing its own 2x scaling before drawing things, then that would throw it off.

**Comment by FyiurAmron** [comment]
@M-HT what you just did is just EPIC :100: I guess it's time to play Albion once again as soon as there's a release ready :D

**Comment by M-HT** [comment]
I'll make a release soon.

**Comment by M-HT** [comment]
Albion release version 1.7.0 contains this and other options for scaling.
