### ISSUE TITLE
Albion: SDL2 Windows version crashes to desktop

### ISSUE THREAD

**Issue by MIuIddy** [M-HT/SR#26]
The SDL1 version works fine, but with the new SDL2 version I get this behavior:

nativewindows/wildmidi/adlmidi:
The game freezes for one second and then exits without an error message, as soon as you can see Tom in his cabin. The crash happens before you could hear any sound, except for the intro, which works fine.

bassmidi:
You can click the text box away and move around in the cabin, but as soon as you interact with anything, the game freezes for one second and then exits without an error message. There is no sound, except for the intro.

sdl_mixer:
Seems to be working fine. No crashes and sound is working.

**Comment by M-HT** [comment]
What version of Windows are you using?

**Comment by MIuIddy** [comment]
Windows 10 Education 20H2

**Comment by M-HT** [comment]
I tested SDL2 version on Windows 10 Education 20H2 and everything worked fine.
In your case, since audio works in the intro and not otherwise, it looks like some problem with sdl_mixer when using midi plugins, but I have no idea what it could be.
You can use the SDL1 version, since it works.

**Comment by MIuIddy** [comment]
I did some additional testing and discovered, that the problem only occurs, when your audio output device is configured to use more than 2 speakers.

**Comment by M-HT** [comment]
I can simulate the crash now, so I'll try to fix the problem.

**Comment by M-HT** [comment]
Albion release version 1.7.1 contains a fix for this issue.
