### ISSUE TITLE
keyboard remapping

### ISSUE THREAD

**Issue by FyiurAmron** [M-HT/SR#27]
A possibility to remap keys (e.g. arrows to WSAD, quite useful for 3D mode) would be great, and shouldn't be too hard considering SDL is already on-board. It's currently doable by generic 3rd party tools for remapping the keyboard system-wide, but a possibility to set this e.g. via config would be even better.

**Comment by M-HT** [comment]
Instead of full key remapping, an option to exchange WSAD and arrow keys should be enough, I think.

**Comment by M-HT** [comment]
Albion release version 1.7.1 contains options to switch WSAD and arrow keys.
