### ISSUE TITLE
Multiple  mouse cursors over the game window? 

### ISSUE THREAD

**Issue by xcom169** [M-HT/SR#29]
Hello All!

Maybe it's just some config parameter, but how can I disable multiple mouse cursors over the game window? I just would like to see the game's cursor, and not the Windows cursors when I'm in the game.

**Comment by M-HT** [comment]
There is a configuration option ```Display_MouseCursor``` to set the shape of the Windows cursor.
Possible values are:
* normal - normal arrow cursor
* minimal - minimal cursor
* none - no cursor
