### ISSUE TITLE
No such file or directory: './seg01.inc'

### ISSUE THREAD

**Issue by jtrees** [M-HT/SR#3]
I'm trying to compile an x86 version of Albion for Linux.

I've compiled SR and moved both `SR.exe` and Albion's `MAIN.EXE` into `SR-games/Albion/SR/x86`. If I then run `builf-x86.sh`, I get the following error:

```
Traceback (most recent call last):
  File "./compact_source.py", line 51, in <module>
    Compact(cPath + "seg01.inc")
  File "./compact_source.py", line 8, in Compact
    fIn = open(cFile, "rt")
IOError: [Errno 2] No such file or directory: './seg01.inc'
```

Apparently the script is expecting some files to be in `SR-games/Albion/SR`. I'm not sure what these files are or where they should be coming from. The instructions don't seem to mention them.

How should I proceed?

**Comment by M-HT** [comment]
You should move `SR.exe` and `MAIN.EXE` into `SR-games/Albion/SR` (not `SR-games/Albion/SR/x86`). Then running `build-x86.sh` should work.

**Comment by jtrees** [comment]
Thanks, it worked! I ran into another problem when launching the game but I'll open a new issue for that.
