### ISSUE TITLE
Septerra Core:  Windows 10 64 bit.  Mouse stutter tied to polling rate?

### ISSUE THREAD

**Issue by Crim001** [M-HT/SR#30]
This SR port of Septerra Core is great!   I've noticed, however that when using my gaming mouse that the mouse stutters constantly. I have realized that it is tied to the mouse polling rate.  If I use my gaming mouse default of 1000 Hz it is very jittery.  Buttery smooth though at 125 Hz. 

I wrote about this experience a bit back on the GOG forums, but have decided to bring it to your attention here in case it may help others who are also having problems with mouse stuttering.

**Comment by M-HT** [comment]
My mouse only has the standard 125 Hz polling rate, so I can't test this.

**Comment by M-HT** [comment]
Can someone test the attached executable whether it fixes the issue ?

[SepterraCore-Windows-x86-test.zip](https://github.com/M-HT/SR/files/7448546/SepterraCore-Windows-x86-test.zip)

**Comment by DukeSkinny** [comment]
Seems to improve things somewhat on my end, but the issue remains.

**Comment by M-HT** [comment]
What about this one ?

[SepterraCore-Windows-x86-test2.zip](https://github.com/M-HT/SR/files/7448918/SepterraCore-Windows-x86-test2.zip)

**Comment by DukeSkinny** [comment]
Brilliant! Completely fixed the issue for me.

**Comment by Crim001** [comment]
I can confirm that the SepterraCore-Windows-x86-test2.zip seems to completely fix the issue.  I no longer need to reduce my mouse polling rate to have smooth mouse movement.  Fantastic, thanks!

**Comment by M-HT** [comment]
Can you please also test this one ?

[SepterraCore-Windows-x86-test3.zip](https://github.com/M-HT/SR/files/7449656/SepterraCore-Windows-x86-test3.zip)

**Comment by DukeSkinny** [comment]
Works like a charm.

**Comment by Crim001** [comment]
Confirmed SepterraCore-Windows-x86-test3.zip also works

**Comment by Zombeaver** [comment]
This fixes the issue for me at 500hz or below but it persists at 1000hz. I tried all 3 versions.

**Comment by M-HT** [comment]
Does test4 also fix the issue ?

[SepterraCore-Windows-x86-test4.zip](https://github.com/M-HT/SR/files/7452444/SepterraCore-Windows-x86-test4.zip)

@Zombeaver Can you  try test5 and test6 if either or both of them fix the issue at 1000Hz ?

[SepterraCore-Windows-x86-test5.zip](https://github.com/M-HT/SR/files/7452446/SepterraCore-Windows-x86-test5.zip)
[SepterraCore-Windows-x86-test6.zip](https://github.com/M-HT/SR/files/7452447/SepterraCore-Windows-x86-test6.zip)

**Comment by DukeSkinny** [comment]
Sadly, no dice with SepterraCore-Windows-x86-test4.zip. The last 2 still perform well.

**Comment by Zombeaver** [comment]
test5 and test6 both fix it for me at 1000hz!

**Comment by Crim001** [comment]
test5 and test6 also fix the mouse issue for me.  Interestingly though, if I have vsync disabled test5 and test6 will make the camera moving that occurs after battle before you get experience/results stutter and take an extended time to happen (test 5 is worse for this).  test3 also does it, but is almost unnoticeable.  Enabling vsync makes it move smoothly after battle like usual.

**Comment by M-HT** [comment]
I released a new version of Septerra Core. I added a new configuration option: CPU_SleepMode. The default value is `standard`. If you have a problem with mouse stuttering (because of higher mouse polling rate) then set the value to `reduced`. If that doesn't fix the problem, then set the value to `nosleep`.

**Comment by JJDrago** [comment]
@M-HT 
I do not know who you are, or where you live, but I will find you and I will marry you.
THANK YOU!
