### ISSUE TITLE
Albion: mouse cursor issues

### ISSUE THREAD

**Issue by lukek19** [M-HT/SR#31]
First of all: Thanks for the amazing port. Having the enhanced 3d rendering is great! However, I noticed two issues with the mouse cursor in the windows port (both SDL1 and SLD2):

- Whenever a new dialogue box is opened, the game pauses for a second or so.  When I run the game in DOSBox, the cursor becomes an hourglass symbol and can still be moved during the pause. In the windows port, the cursor does not change to the hourglass symbol and freezes for a second.
- In both the windows port and in DOSBox, the game seems to be running at 20 FPS in the 2d parts. In DOSBox, however, the 20 FPS cap does not seem to affect the cursor movement. When I just run around with the cursor in one place, I get a constant 20 FPS. But as soon as I move the mouse quickly, the framerate goes up to 60 (whilst the game itself doesn't speed up or anything)! In the windows port, the framerate is always locked to 20, and therefore cursor movement seems quite laggy during the 2d parts. it would also be great to have an option to change mouse movement speed.

**Comment by M-HT** [comment]
I can confirm the first point - I'll take a look at it, but it has low priority.

Regarding the second point - how do you get those numbers ? How do you measure them?

**Comment by lukek19** [comment]
I simply used MSI Afterburner to measure the framrate. I guess it measures how frequently the screen image is updated. So when I stand around in a 2D area, where nothing is happening on screen (i.e. nobody's moving and no animation), then it displays 0 FPS. As soon as I start moving around or other NPCs on screen are moving the framerate goes up to 20 FPS (which makes me think that the game itself runs at 20 FPS in 2D mode). Now here's the difference between it running in DosBox and the SR Port: When I move the mouse in DosBox, the FPS go up (max. 60) and the cursor movement seems very smooth. In the Windows Port, the mouse movement is very sluggish and the FPS stays at 20 no matter how fast I move it. Honestly I'm not sure if it is the FPS cap that makes the mouse stutter, or if it is because of the mouse stuttering that I don't see larger FPS values!

Also the mouse movement (even in the 3D parts where it's completely smooth) seems to be a bit slower compared to outside of the game. So whenever I start the game, I first increase my cursor movement speed to max in the windows settings, and then decrease it back when I close the game. Hence it would be nice to have the option to adjust mouse cursor speed in the config file, if can be implemented easily! if not... it's really not that big of a deal ;)

**Comment by M-HT** [comment]
I created a new release which contains the fix.
