### ISSUE TITLE
Septerra Core: Which data files are needed on Linux ? 

### ISSUE THREAD

**Issue by xcom169** [M-HT/SR#35]
Hello,

Septerra Core: Which data files are needed on Linux from the GOG version ?

Thanks,

**Comment by M-HT** [comment]
The game files are in the subdirectory `game/Game` of the install directory.

**Comment by xcom169** [comment]
Thanks! 

QuickTime is needed for Linux in SR-Septerra ? 
/SR-Septerra: error while loading shared libraries: libquicktime.so.2: cannot open shared object file: No such file or directory

**Comment by M-HT** [comment]
Quoting from readme-Linux.txt:
```
The game requires following 32-bit libraries: SDL2, mpg123, quicktime2
On debian based distributions these libraries are in following packages: libsdl2-2.0-0:i386 libmpg123-0:i386 libquicktime2:i386
```

**Comment by xcom169** [comment]
Thanks!
