### ISSUE TITLE
Game suggestions: Prehistorik 1, Oregon Trail Deluxe, The Settlers 

### ISSUE THREAD

**Issue by xcom169** [M-HT/SR#37]
Maybe they are childish DOS games, but they were very popular in their times. Neither they have any source-ports currently.
I don't have OpenPandora but they are also very good for handheld systems, because the controls are easy.

**Comment by M-HT** [comment]
Prehistorik 1 and Oregon Trail Deluxe are 16-bit programs which aren't supported by this project.
