### ISSUE TITLE
Septerra Core: Slower, significantly lower pitched audio in 1.04.0.6

### ISSUE THREAD

**Issue by DukeSkinny** [M-HT/SR#39]
While the latest update fixed the mouse stutter issue, all music now runs much slower and at quite a lower pitch. This can be heard as early as the main menu.
Tried Vsync on and off, as well as all CPU_SleepMode options. No dice.

1.04.0.5 is verified as working.

**Comment by M-HT** [comment]
I reverted back to previous version of SDL2 to fix the issue. I uploaded a new version for Windows to the releases - please download it.
