### ISSUE TITLE
Xload: File does not exist. (Name : Slab)

### ISSUE THREAD

**Issue by jtrees** [M-HT/SR#4]
After moving `SR-Main` (self-compiled) and `Albion.cfg` and `Albion.sh` from `games/Albion/release/linux/` to the game directory and launching the startup script (`./Albion.sh`) I get the following error:

```
Using config file: Albion.cfg
An error has occurred.
Please examine the file ERROR.LOG.
```

#### Contents of error.log

```
**** Error log ****

Albion v1.38 (created on Jul 25 1996 12:39:09)
Executed on Sun Mar  3 16:47:05 2019

BBERROR: ERRORSTACK START:--------------
BBDOS Library:  DOS_setcurrentdir: unknown error - FILENAME: D:\ALBION - DATA: 0 - OSERROR: 2
Xload: File does not exist.
     (Name : Slab)
Albion: File access error.
(line 679 of file g:\albion\src\game.c)
BBERROR: ERRORSTACK END-----------------


Please read the README.TXT file to find out how to contact
the Blue Byte hotline.
```

Any ideas? What's the problem here?

I'm using an unchanged `Albion.cfg` from the repo by the way.

**Comment by M-HT** [comment]
Create directory `ALBIONCD` in the game directory. Copy the content of directory `ALBION` on cdrom into `ALBIONCD`. (If you have Albion from GOG.com then the file game.gog is the image of the CD in BIN format.)
In file `SETUP.INI` find line which begins with `SOURCE_PATH=` and replace it with line `SOURCE_PATH=ALBIONCD\` .
That should allow the game to run. 
After that, you should configure the game either by editing `Albion.cfg` directly or by using the configuration utility (run `./pycfg.py albion pc Albion.cfg`).

BTW this and other things are explained in file `readme-Linux.txt` which is in the Linux release file. I should probably add it to the sources.

**Comment by jtrees** [comment]
Cool, thanks! I can now use the startup script to play the intro video. The game doesn't run after the video though. I get this:

```
SETUP_INI=SETUP.INI
ALBION_EXE=ALBION.EXE
ALBIONCD=ALBIONCD
ALBIONCD_ROOT=
FILE_RESULT=INTRO.SMK
INTRO_PLAY=on
Using config file: Albion.cfg
Please insert the Albion CD in your CD-ROM drive.
```

**Comment by M-HT** [comment]
Can you try the compiled Linux release and test if it works or not ?

**Comment by jtrees** [comment]
I get exactly the same with the compiled release.

**Comment by M-HT** [comment]
Can you post the content of file `SETUP.INI` and the result of command `ls -lR` from the game directory ?

**Comment by jtrees** [comment]
#### SETUP.INI

```
[SYSTEM]
VESA=Y
FPU=Y
SOURCE_PATH=ALBIONCD\
LANGUAGE=2
[VESA]
MODE_1024x768x16.2M=y
MODE_800x600x16.2M=Y
MODE_640x480x16.2M=Y
MODE_1024x768x64k=Y
MODE_800x600x64k=Y
MODE_640x480x64k=Y
MODE_1024x768x32k=Y
MODE_800x600x32k=Y
MODE_640x480x32k=Y
MODE_1024x768x256=Y
MODE_800x600x256=Y
MODE_640x480x256=Y
MODE_640x400x256=Y
MEMORY=2097152
VESA_VERSION_SUBNUMBER=0
VESA_VERSION_NUMBER=2
OEM=S3 Incorporated. Trio64
[ALBION]
SAVED_GAME_NR=1
MIDI_VOLUME=127
DIGI_VOLUME=127
3D_WINDOW_SIZE=100
COMBAT_DETAIL_LEVEL=3
COMBAT_MESSAGE_SPEED=10
```

#### ls -lR

[output](https://0bin.net/paste/AizhHO824ARF3y+b#rJSxLDA9mMs0XeizhTdOVp52H4+7FohKl7qpNP87R+G)

**Comment by M-HT** [comment]
I see the problem. You copied the content of cdrom into `ALBIONCD` directory. You should copy the content of `ALBION` directory on cdrom into `ALBIONCD` directory.

**Comment by jtrees** [comment]
#### SETUP.INI

```
[SYSTEM]
VESA=Y
FPU=Y
SOURCE_PATH=ALBIONCD\
LANGUAGE=2
[VESA]
MODE_1024x768x16.2M=y
MODE_800x600x16.2M=Y
MODE_640x480x16.2M=Y
MODE_1024x768x64k=Y
MODE_800x600x64k=Y
MODE_640x480x64k=Y
MODE_1024x768x32k=Y
MODE_800x600x32k=Y
MODE_640x480x32k=Y
MODE_1024x768x256=Y
MODE_800x600x256=Y
MODE_640x480x256=Y
MODE_640x400x256=Y
MEMORY=2097152
VESA_VERSION_SUBNUMBER=0
VESA_VERSION_NUMBER=2
OEM=S3 Incorporated. Trio64
[ALBION]
SAVED_GAME_NR=1
MIDI_VOLUME=127
DIGI_VOLUME=127
3D_WINDOW_SIZE=100
COMBAT_DETAIL_LEVEL=3
COMBAT_MESSAGE_SPEED=10
```

#### ls -lR

[output](https://0bin.net/paste/AizhHO824ARF3y+b#rJSxLDA9mMs0XeizhTdOVp52H4+7FohKl7qpNP87R+G)

**Comment by jtrees** [comment]
Aw friggin sweet, it works!

Thank you for your patience.

**Comment by billbeans** [comment]
For those that might be reading this in the future, the files `SLAB.` and `ITEMGFX.` have a period at the end which causes the program to fail finding them. I'm not sure how they got named that way. I used PowerISO to extract the files from a bin+cue image. Simply renaming them to remove the trailing stop fixes the issue.
