### ISSUE TITLE
Albion: Movement with keyboard is buffered and thus automatically skips popup dialogs

### ISSUE THREAD

**Issue by solaris32** [M-HT/SR#40]
Movement keys, among other keys, can be used to skip dialog. When moving with the keyboard, whether it is the arrow keys or wasd as enabled in the config file, the skip dialog feature of those buttons seems to be buffered or extended, and so when a dialog popup occurs it only shows for a brief moment before automatically disappearing or being skipped, even though you already let go of the movement key.

Furthermore, while in a long dialog, if you hold down any key it is extended for a long while resulting in large amounts of dialog boxes being skipped even though you let go of the key several seconds prior. 

This can be easily tested at the beginning of the game which has the long conversation with Christine, and a few automatic popup dialogs on the right side of the ship.

I have tested and this does not happen in the gog version: as long as you let go of a key before the hourglass loading cursor ends, the dialog will not be skipped. Nor can you buffer multiple skips; it will stop skipping as soon as you let go of the key.

Honestly cannot play the game like this. 

Running latest Gog version, running your code 1.7.1 sdl2, windows 10.

**Comment by M-HT** [comment]
The sdl1 version works correctly, so you can use that. I'll have to check the sdl2 version.

**Comment by solaris32** [comment]
> The sdl1 version works correctly, so you can use that. I'll have to check the sdl2 version.

You are correct, sdl1 works just fine. Thank you for the super fast response, and thank you for caring about this amazing game for all these years. You are still helping people to this day :).

**Comment by M-HT** [comment]
I fixed it in code, but I won't make a new release at the moment.

**Comment by M-HT** [comment]
I created a new release which contains the fix.
