### ISSUE TITLE
What's the difference between SDL1 and SDL2 in Albion?

### ISSUE THREAD

**Issue by Arthandas** [M-HT/SR#41]
Probably the stupid question but I have no idea which archive to use.
I'm setting up the GOG version on Win 10.

**Comment by M-HT** [comment]
The difference is the version of [SDL](https://www.libsdl.org/) library which is used - 1.2 or 2.0.
In most situations both versions work the same. If one doesn't work for you, try the other one.

**Comment by Arthandas** [comment]
Thank you.

**Comment by Arthandas** [comment]
Thank you.
