### ISSUE TITLE
Septerra Core "desktop" display mode enhancement

### ISSUE THREAD

**Issue by johnnovak** [M-HT/SR#42]
Currently, when using the "desktop" display mode, the width & height values are ignored and the image output is stretched to the desktop resolution (with the correct 4:3: aspect ratio).

What I would like, though, is to be able to set width & height to 1280x960 while using the desktop mode. Effectively, the image would be displayed centered on the screen with a 2x integer scaling ratio when using "basicnb" mode.

Now the only way to achieve this is to use windowed mode, which is fine, but this would be a nice enhancement and pretty easy to do, I assume.

**Comment by M-HT** [comment]
I added an option to only use integer scaling, which allows to get the desired result.

**Comment by johnnovak** [comment]
Great, thanks a lot!

**Comment by johnnovak** [comment]
I assume you'll release a new binary with the change in the near future?

**Comment by M-HT** [comment]
I created a new release.
