### ISSUE TITLE
16-bit exe file support broken?

### ISSUE THREAD

**Issue by plaes** [M-HT/SR#43]
Seems like SR only supports LE executables?

I tried to run SR against exe files from both Covert Action and Centurion: Defender of Rome (exe file for that game needs to be unpacked first with unp) but ran into various "file too small" or "invalid EXE file" errors.

**Comment by M-HT** [comment]
SR only supports 32-bit code (by design). Also, in case it's not  clear, it's not a complete disassembling tool - you need to provide some information about the executable to get a working result. And conversion to Windows/Linux is another issue altogether.

**Comment by jan-kleks** [comment]
A write-up about the process could be an interesting thing to read...

**Comment by jan-kleks** [comment]
And BTW @M-HT, it looks like people on reddit really like your project: https://old.reddit.com/r/emulation/comments/sjwb6m/sr_srw_project_by_mht_to_statically_recompile/

**Comment by M-HT** [comment]
> A write-up about the process could be an interesting thing to read...

I'm more into writing code than writing texts, so the probability of me writing something like that any time soon is very low.

> And BTW @M-HT, it looks like people on reddit really like your project: https://old.reddit.com/r/emulation/comments/sjwb6m/sr_srw_project_by_mht_to_statically_recompile/

I noticed an increased interest in the project and was wondering where it came from - that's most probably it.

**Comment by jan-kleks** [comment]
> I'm more into writing code than writing texts, so the probability of me writing something like that any time soon is very low.

I can see your point. But please take into consideration that such a write-up could potentially inspire someone start their own cool retro coding project, or help you find a dev willing to contribute to SR.

Anyway, keep up the great work!

**Comment by xor2003** [comment]
for 16-bit check my project [translator](https://github.com/xor2003/masm2c) [hw_support](https://github.com/xor2003/libdosbox)
