### ISSUE TITLE
Is it possible to use this project as a general toolchain ?

### ISSUE THREAD

**Issue by velteyn** [M-HT/SR#44]
Hello, I have a question, I see that this project is focused on some old DOS games.
My question is: is it possible to use this project toolchain to reverse **any** old DOS games?
For example: I would like to extract and study the Dynamic Mission Generator from DiD Eurofighter 2000 (an old DOS game form '90s)

How can I approach the problem?
Thank you

**Comment by M-HT** [comment]
>  My question is: is it possible to use this project toolchain to reverse any old DOS games?

No.
This project only supports 32-bit code, which rules out 16-bit games.
And ideally the program would produce the result without knowing anything about how the game works.
That isn't possible, so the program needs to know some information about the game, mainly about input (keyboard, mouse) and output (video, audio).
The program doesn't need any information about game logic and doesn't provide any means to find it.
