### ISSUE TITLE
Can't compile Albion for LLasm

### ISSUE THREAD

**Issue by IS4Code** [M-HT/SR#51]
I am getting an error when compiling Albion for the LLVM target:
```
./SR.exe ALBION.EXE out

Output type: LLasm version
esp dword aligned: no
ebp dword aligned: no
2022-12-20 02:33:17.555: Loading EXE file...
        Sections in file: 8
2022-12-20 02:33:17.563: Loading source code information...
2022-12-20 02:33:17.563: Initial disassembly...
2022-12-20 02:33:17.857: Applying fixup...
2022-12-20 02:33:17.909: Full disassembly...
Error: unknown flags on start of region - 0 - 32084 (0x17d54) - 0x38
Error: 
```
The x86 target is compiled successfully. I am using CentOS 8.

**Comment by IllidanS4** [comment]
Is it possible to make it working with llasm, please?

**Comment by M-HT** [comment]
What would you use it for ?

**Comment by IllidanS4** [comment]
I am thinking about making Albion run in the browser, by compiling the LLVM IR to WebAssembly, if that is possible...

**Comment by M-HT** [comment]
I don't know if that's possible or not. Maybe you can first try to compile something which already supports llasm target - the intro executable from X-Com: UFO Defense (UFO: Enemy Unknown) or Septerra Core: Legacy of the Creator.

**Comment by IllidanS4** [comment]
Well, at the moment I don't have much luck compiling UFO: Enemy Unknown either:

```
./SR.exe INTRO.EXE intro-asm.llasm
Output type: LLasm version
esp dword aligned: yes
ebp dword aligned: yes
2022-12-20 13:24:11.729: Loading EXE file...
        Sections in file: 3
2022-12-20 13:24:11.730: Loading source code information...
        Loading fixup_interpret_as_code.sci...
        Loading external_procedures.sci...
        Loading global_aliases.sci...
        Loading instruction_replacements.sci...
2022-12-20 13:24:11.730: Initial disassembly...
2022-12-20 13:24:11.744: Applying fixup...
2022-12-20 13:24:11.747: Full disassembly...
Error: output not found - 0 - 0x7fa
Error: 1
```

MD5 of INTRO.EXE: ad8322dec6c8f09a2ffebd8d4977d779

**Comment by M-HT** [comment]
That's probably because you have a different INTRO.exe.

Required INTRO.EXE is from the DOS English version 1.4.
* file size: 74314 bytes
* md5: 28098b9411d9454ad6676d99cefc0e4b
* sha1: 927f0896dc91eea3b948ad60ed71870843ce5ad0
* sha256: 513569ceea82ee0b265cad3605b82324ac1adcd98adbff7f6ce0fbef7af4da30

**Comment by IllidanS4** [comment]
Thanks, I had to found a patch to 1.4, but now I can't find gdc to compile llasm. Could you please upload a binary of it somewhere?

**Comment by M-HT** [comment]
Try this one:
[llasm.tar.gz](https://github.com/M-HT/SR/files/10275690/llasm.tar.gz)

**Comment by xcom169** [comment]
Hello All!

Did you try Nasm 2.16 ? Is it working well with SR?

**Comment by M-HT** [comment]
Nasm 2.16 works with SR. The bug present in versions 2.15.03 -- 2.15.05 was fixed.

**Comment by IllidanS4** [comment]
> Try this one: [llasm.tar.gz](https://github.com/M-HT/SR/files/10275690/llasm.tar.gz)

Thank you! I managed to compile it, and now I am trying to get SDL2 work in emscripten. So far it seems like `SDL_CreateSemaphore` is not working... I'll update when I get it to work.

I also found an error possibly unrelated to WASM:
```
Uncaught RuntimeError: null function or function signature mismatch
    at MidiPlugin_Shutdown (Intro-music-midiplugin.c:584:5)
    at Game_Cleanup (main.c:875:21)
    at Game_Initialize (main.c:1165:9)
    at main (main.c:1919:24)
```

Perhaps `MP_functions.shutdown_plugin` does not exist yet at this point in `Game_Initialize`?

**Comment by IllidanS4** [comment]
Well I got it to a [point](https://is4.site/SR-Intro/SR-Intro.html) where it runs a few events and then quits. Not sure where to go from there...

**Comment by M-HT** [comment]
Either find a way to debug it or add printf statements to the code to see where it stops executing.

As for the error - it occurs when the game fails to initialize. I'll fix it, but it's not what prevents the game from running.

**Comment by IllidanS4** [comment]
Seems to be exitting from `X86_InPortProcedure`:
```
out 0x43
size 1
eax 0x63736d65
al 0x65
```
I have suppressed that situation with `return;` but now recursion is the problem:
```
RangeError: Maximum call stack size exceeded
    at X86_OutPortProcedure (Intro-inout.c:66:1)
    at x86_out_imm_al (llasm_inout.c:82:46)
    at .Lloc_110B0 (llasm_stos.c:43:1)
    at .Lloc_11091 (llasm_stos.c:43:1)
    at .Lloc_110B0 (llasm_stos.c:43:1)
    at .Lloc_11091 (llasm_stos.c:43:1)
    at .Lloc_110B0 (llasm_stos.c:43:1)
    at .Lloc_11091 (llasm_stos.c:43:1)
    at .Lloc_110B0 (llasm_stos.c:43:1)
    at .Lloc_11091 (llasm_stos.c:43:1)
```
I suppose this is a good time to mention that I had to remove `musttail` from the generated LLVM code, since WebAssembly does not support tail-calls yet. I had hoped performance would be all that would affect, but if the code cannot run properly without it, we may need to wait a few years before tail-calls become supported.

**Comment by M-HT** [comment]
When a target doesn't support tails-calls, then use llasm with parameter `-no-tail-calls`, which generates slower code without tails-calls. You can't just remove `musttail` without doing anything else, otherwise you get infinite recursion.

`X86_InPortProcedure` doesn't have such debug text - that's debug text from `X86_OutPortProcedure`.

**Comment by IllidanS4** [comment]
Thanks! Yeah I meant `X86_OutPortProcedure`, but copied the wrong name.

`-no-tail-calls` has fixed the recursion, and now it even seems to be launching somewhat, I can see it open the UFOINT.FLI file, but nothing is drawn to the screen and it quits after a short while, with this
```
Simulating Real Mode Interrupt: 66h
Running Original Interrupt...
Running function: eax=0x101
DIGPAK: stopping sound
Exit code: 7799984
```

**Comment by IS4Code** [comment]
@M-HT 
Hello! I noticed you made Albion compilable for llasm, thanks! I decide to try it again, using a similar approach as last time, with `-no-tail-calls` etc., but I am getting signature mismatch warnings from `emcc`:
```
wasm-ld: warning: function signature mismatch: Game_dos_setvect
>>> defined as (i32, i32, i32) -> i32 in llasm/SR-asm-calls.o
>>> defined as (i32, i32, i32) -> void in Albion-proc.o

wasm-ld: warning: function signature mismatch: lseek
>>> defined as (i32, i32, i32) -> i32 in llasm/SR-asm-calls.o
>>> defined as (i32, i64, i32) -> i64 in /root/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc-mt-debug.a(lseek.o)

wasm-ld: warning: function signature mismatch: Game_setbuf
>>> defined as (i32, i32) -> i32 in llasm/SR-asm-calls.o
>>> defined as (i32, i32) -> void in Albion-proc.o

wasm-ld: warning: function signature mismatch: time
>>> defined as (i32) -> i32 in llasm/SR-asm-calls.o
>>> defined as (i32) -> i64 in /root/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc-mt-debug.a(emscripten_time.o)

wasm-ld: warning: function signature mismatch: Game_filelength
>>> defined as (i32) -> i32 in llasm/SR-asm-calls.o
>>> defined as (i32) -> i64 in Albion-proc.o

wasm-ld: warning: function signature mismatch: Game_dos_getvect
>>> defined as (i32) -> i32 in llasm/SR-asm-calls.o
>>> defined as (i32) -> i64 in Albion-proc.o

wasm-ld: warning: function signature mismatch: Game_tell
>>> defined as (i32) -> i32 in llasm/SR-asm-calls.o
>>> defined as (i32) -> i64 in Albion-proc.o
```
I was also getting an error due to `fcloseall` missing, but I solved that temporarily by removing the call to it.

Due to the warnings, I am getting `signature_mismatch:Game_dos_getvect` at runtime and can't run it.

Could you please help me with resolving the warnings (and finding a better replacement for `fcloseall`)?

**Comment by M-HT** [comment]
Try it with the latest commits. The warnings and missing function fcloseall should be fixed.

**Comment by IS4Code** [comment]
Compiles fine, thank you! Now I just need to figure out why it renders as a black screen (though the main loop works) but that is up to Emscripten now...
