### ISSUE TITLE
Albion without a mouse (Steam Deck)

### ISSUE THREAD

**Issue by BumbleCast** [M-HT/SR#52]
Thanks for your amazing work.
From a technical point of view, would it be possible to make the game 'mouse-free', so that it can be played with a controller without the need of a mouse?

I am considering getting a Steam Deck. While I don't see any problems with installing the Linux port of Albion (has anyone already gone through the process?), the above-mentioned mouse-free option would make the mobile gaming experience much better. 

 Given that Albion wasn't designed to be played this way, it is more of a general question.

**Comment by M-HT** [comment]
The only way of playing without a mouse is to simulate the mouse inputs (movement, left+right button).
