### ISSUE TITLE
Albion: More mouse cursor issues

### ISSUE THREAD

**Issue by lukek19** [M-HT/SR#54]
Thanks for fixing issue #31. The mouse cursor now moves a lot more smoothly. Also, the issue with the hourglass cursor seems to be fixed!

However, I noticed a couple more issues concerning the mouse movement in this game:

1.  When running the game in window mode and setting _Display_MouseCursor_ to either "normal" or "minimal", you can see that the in-game mouse cursor is slightly lagging behind the actual SDL mouse cursor. I wonder if this is fixable, since I played this game a lot on both original hardware and in DosBox, and the mouse movement in the Windows port "just doesn't feel quite right" yet.

2. When playing in fullscreen and setting the aspect ratio to anything lower than your screen's native AR (for me this would be 16:9), the mouse seems to "get stuck" in the black vertical bar on the left hand side. More precisely, when you move the mouse all the way to the left and then start moving it right again, it takes a while until the mouse cursor starts to respond. Strangely, this does not happen at the right border. Here are two additional observations, that may or may not be helpful: 
- This does NOT happen when you move the mouse all the way to the bottom left corner. If it is there, the cursor immediately starts moving when moving the mouse to the right.
- When you set the aspect ratio to anything less than 1 (e.g. 1:2, although I don't know why anyone would want to do this), then the same thing starts to happen at the right border (but again - not, if you move the mouse all the way to the bottom right).

I am running the latest release v1.7.2 on Windows 10 and the issues happen in both the SDL1 and SDL2 version.

**Comment by M-HT** [comment]
1. That's the way it's implemented. Nothing to be done here.
2. I'll fix this, but I want to do some other things before making a release.

**Comment by M-HT** [comment]
I made a new release which contains this fix:
https://github.com/M-HT/SR/releases/tag/albion_v1.7.3
