### ISSUE TITLE
No mouse movement/keyboard input in Warcraft / Linux

### ISSUE THREAD

**Issue by xcom169** [M-HT/SR#55]
Hello All,

I'm experiencing no mouse movement/keyboard input in Warcraft I.  on  Linux. 
Is it a known problem?

![image](https://user-images.githubusercontent.com/17802090/225058059-8a56f20f-b422-400e-a61f-e2fb93afa4ad.png)

Thanks a lot!

**Comment by M-HT** [comment]
It works for me without any problems.
What version are you using - x86/arm; SDL1/SDL2 ? What Linux distribution ? What game version - floppy/CD ?
And does the original executable WAR.EXE match supported executables ?

**Comment by xcom169** [comment]
Hello!  I tried with the latest Arch Linux with NASM 2.16.01 . I used the CDGOD version.   I used the default SDL version, I think it's 2.26.4 

The game plays, but no input is possible. Strange.

**Comment by M-HT** [comment]
When compiling, did you use parameter `sdl2=1` ? Something like `scons sdl2=1 version=cdgog`.
If not then compile it with the parameter.

**Comment by xcom169** [comment]
Thanks! It's okay with sdl2 .
