### ISSUE TITLE
XCOM Terror from the deep versions

### ISSUE THREAD

**Issue by xcom169** [M-HT/SR#56]
Hello All!

For 'XCOM Terror from the deep '  can I use the GOG version which is v2.1?  
I tried to use it, but it looks the hashes are different: 

UFO2EXE sha256sum TACTICAL.EXE 
983f1c0d748049c3914cc595ebbd54f86d1f9709348c8b1945fa1b5584de7bad  TACTICAL.EXE

sha256sum GEOSCAPE.EXE 
490f8d271dda18c7ea1e9aff42b235ba62a9965ca9e26141c93a57c675ed6894  GEOSCAPE.EXE

![image](https://user-images.githubusercontent.com/17802090/227780244-ac1f1ca6-e905-425c-8376-1de6bd4d5e93.png)

Where can I buy a version which is working with SR?

Thanks!

**Comment by M-HT** [comment]
The GOG executables look quite different. I'll have to add support for them.

**Comment by M-HT** [comment]
I added support for the executables from GOG.com.

**Comment by xcom169** [comment]
It's running:
![image](https://user-images.githubusercontent.com/17802090/230346284-ea695c06-8dd7-43bf-8492-2f89100875de.png)


really nice.
