### ISSUE TITLE
Question on running Albion 64bit

### ISSUE THREAD

**Issue by throgh** [M-HT/SR#58]
Hello,

I have compiled so far SR-Main under 64bit (no multilib) and want to run it with SR64-loader. But I get always the following error on the terminal:

`Error mmaping memory`

This is clearly to be identified on SR64-loader.c:

`
    if (FAILED_MMAP(mem))
    {
        pr_errprint("Error mmaping memory\n");
        return -1;
    }
`

Is something missing on the way to start the application? Something needed on the base-system?
Perhaps a bit more information would help here to identify where the issue is. Thanks!

**Comment by M-HT** [comment]
What platform and operating system are you using to run Albion ?

**Comment by throgh** [comment]
GNU/Linux, 64bit (Hyperbola 0.4 to be exactly)

**Comment by M-HT** [comment]
I fixed a problem in the loader. Can you test it, if it resolves the issue ?

**Comment by throgh** [comment]
Outstanding: Game is now working. Thanks for your work!
That 64bit-mode is helping a lot to get those gems working.
