### ISSUE TITLE
Septerra Core (Steam) crashes on Win10

### ISSUE THREAD

**Issue by mitharas** [M-HT/SR#59]
Hi,  
  
unfortunately, I can't get this to run on my system. When I execute SR-Septerra.exe, the videos play just fine. After that there's a black screen for a few seconds (or less, dependant on video settings) and the exe closes.  
  
I have tried the following without success:  

- changed the config to disable intro and vsync
- run as admin
- run in compatibility mode for 7 and xp sp3
- Delete the game folder, redownload via steam, redownload patch from here and copy files
- checked event viewer, but there are no entries I could find  

I'm not sure if I can analyze this any further. Maybe relevant system information:  
OS: Win10 Pro Build 19044.2846 (21H2 with Updates from 2023-04)
CPU: AMD Ryzen 5 1600
Video: GeForce GTX 1060  
  
I hope this has some simple fix. I'd be glad to assist in further troubleshooting, but I'm out of ideas.

**Comment by M-HT** [comment]
Just to make sure: you're downloading version v1.04.0.7 from [here](https://github.com/M-HT/SR/releases/tag/septerra_v1.04.0.7) and you're running the game using `SR-Septerra.exe` ?

Compatibility mode shouldn't be needed to tun the game.

One thing you can try is downloading the latest SDL2 version from [here](https://github.com/libsdl-org/SDL/releases/tag/release-2.26.5) (`SDL2-2.26.5-win32-x86.zip`) and replace SDL2.dll that is bundled with version v1.04.0.7.

If that doesn't help, can you post a complete listing (command `dir /s`) of Septerra Core's directory ?

**Comment by mitharas** [comment]
Thanks for the fast response.

> Just to make sure: you're downloading version v1.04.0.7 from [here](https://github.com/M-HT/SR/releases/tag/septerra_v1.04.0.7) and you're running the game using SR-Septerra.exe ?  
  
Yep. The exact link I used was [this](https://github.com/M-HT/SR/releases/download/septerra_v1.04.0.7/SepterraCore-Windows-x86-v1.04.0.7.zip)  
  

> One thing you can try is downloading the latest SDL2 version from [here](https://github.com/libsdl-org/SDL/releases/tag/release-2.26.5) (SDL2-2.26.5-win32-x86.zip) and replace SDL2.dll that is bundled with version v1.04.0.7.  
  
I did this just now and it didn't change the behaviour.  
  
> If that doesn't help, can you post a complete listing (command dir /s) of Septerra Core's directory ?  
   
Here you go: [dir.txt](https://github.com/M-HT/SR/files/11364553/dir.txt)  
Note that my system is german (as well as septerra cores language). I may have forgotten to mention that. If it helps, I could try changing the language.  
 
` Datentr„ger in Laufwerk D: ist 1TB
 Volumeseriennummer: 9CE8-94A5

 Verzeichnis von D:\SteamLibrary\steamapps\common\Septerra Core

30.04.2023  22:08    <DIR>          .
30.04.2023  22:08    <DIR>          ..
30.04.2023  22:04        74.484.301 anim.db
11.10.2019  17:38         7.235.355 avcodec-54.dll
11.10.2019  17:38           309.149 avutil-52.dll
30.04.2023  22:05    <DIR>          directx
30.04.2023  22:04             2.125 InstallScript.vdf
30.04.2023  22:04       226.746.257 level.db
07.10.2019  14:09            14.336 libdl.dll
30.08.2013  05:44            95.744 libgcc_s_sjlj-1.dll
11.10.2019  12:18         1.009.152 libintl.dll
08.01.2022  13:30           343.692 libmpg123-0.dll
11.10.2019  18:21           970.240 libquicktime.dll
30.08.2013  10:28            75.496 libwinpthread-1.dll
11.10.2019  18:21            48.128 lqt_audiocodec.dll
11.10.2019  18:24           108.032 lqt_ffmpeg.dll
11.10.2019  18:22            52.224 lqt_rtjpeg.dll
11.10.2019  18:22            39.424 lqt_videocodec.dll
30.04.2023  22:04        32.968.764 M1.DB
30.04.2023  22:04        59.914.536 M10.DB
30.04.2023  22:04        24.346.520 M2.DB
30.04.2023  22:04         3.369.686 M3.DB
30.04.2023  22:04         8.843.104 M4.DB
30.04.2023  22:04         5.850.614 M5.DB
30.04.2023  22:04         2.536.074 M6.DB
30.04.2023  22:04         3.200.730 M7.DB
30.04.2023  22:04        12.482.272 M8.DB
30.04.2023  22:04        24.243.996 M9A.DB
30.04.2023  22:04        29.265.584 M9B.DB
30.04.2023  22:04         4.655.317 Manual.pdf
30.04.2023  22:04         2.502.586 MONOLITH.DB
30.04.2023  22:05    <DIR>          qt
25.07.2019  09:36               433 README-SDL.txt
08.01.2022  11:28             1.685 readme-Windows.txt
30.04.2023  22:04             7.696 readme.txt
30.04.2023  22:08    <DIR>          savedata
05.04.2023  20:46         2.296.320 SDL2.dll
30.04.2023  22:08             2.696 Septerra.cfg
30.04.2023  22:04           939.076 septerra.db
30.04.2023  22:04           729.088 septerra.exe
30.04.2023  22:04           220.992 septerra.idx
01.05.2023  10:57               643 septerra.ini
30.04.2023  22:04               387 septerra.mft
30.04.2023  22:04       206.164.329 sound.db
08.01.2022  13:33           943.137 SR-Septerra.exe
11.10.2019  17:39           382.235 swscale-2.dll
30.04.2023  22:04           396.030 text.db
30.04.2023  22:04         1.946.954 topware.db
30.04.2023  22:05           184.376 tp_strip.bmp
30.04.2023  22:04         2.481.622 valkyrie.db
              45 Datei(en),    742.411.137 Bytes

 Verzeichnis von D:\SteamLibrary\steamapps\common\Septerra Core\directx

30.04.2023  22:05    <DIR>          .
30.04.2023  22:05    <DIR>          ..
30.04.2023  22:04         1.078.954 Apr2005_d3dx9_25_x86.cab
30.04.2023  22:04         1.115.221 Apr2006_d3dx9_30_x86.cab
30.04.2023  22:04           916.430 Apr2006_MDX1_x86.cab
30.04.2023  22:04         4.162.630 Apr2006_MDX1_x86_Archive.cab
30.04.2023  22:04           133.095 Apr2006_XACT_x86.cab
30.04.2023  22:04            46.002 Apr2006_xinput_x86.cab
30.04.2023  22:04           695.857 APR2007_d3dx10_33_x86.cab
30.04.2023  22:04         1.606.031 APR2007_d3dx9_33_x86.cab
30.04.2023  22:04           151.225 APR2007_XACT_x86.cab
30.04.2023  22:04            53.294 APR2007_xinput_x86.cab
30.04.2023  22:04         1.077.644 Aug2005_d3dx9_27_x86.cab
30.04.2023  22:04           137.235 AUG2006_XACT_x86.cab
30.04.2023  22:04            46.058 AUG2006_xinput_x86.cab
30.04.2023  22:04           796.859 AUG2007_d3dx10_35_x86.cab
30.04.2023  22:04         1.708.144 AUG2007_d3dx9_35_x86.cab
30.04.2023  22:04           153.004 AUG2007_XACT_x86.cab
30.04.2023  22:04           849.167 Aug2008_d3dx10_39_x86.cab
30.04.2023  22:04         1.464.664 Aug2008_d3dx9_39_x86.cab
30.04.2023  22:04            92.996 Aug2008_XACT_x86.cab
30.04.2023  22:04           271.038 Aug2008_XAudio_x86.cab
30.04.2023  22:04           900.598 Aug2009_D3DCompiler_42_x86.cab
30.04.2023  22:04         3.319.732 Aug2009_d3dcsx_42_x86.cab
30.04.2023  22:04           192.131 Aug2009_d3dx10_42_x86.cab
30.04.2023  22:04           105.036 Aug2009_d3dx11_42_x86.cab
30.04.2023  22:04           728.456 Aug2009_d3dx9_42_x86.cab
30.04.2023  22:04            93.098 Aug2009_XACT_x86.cab
30.04.2023  22:04           272.634 Aug2009_XAudio_x86.cab
30.04.2023  22:04         1.155.483 BDANT.cab
30.04.2023  22:04           975.148 BDAXP.cab
30.04.2023  22:04         1.079.448 Dec2005_d3dx9_28_x86.cab
30.04.2023  22:04           191.712 DEC2006_d3dx10_00_x86.cab
30.04.2023  22:04         1.574.376 DEC2006_d3dx9_32_x86.cab
30.04.2023  22:04           145.591 DEC2006_XACT_x86.cab
30.04.2023  22:04            94.024 DSETUP.dll
30.04.2023  22:04         1.691.464 dsetup32.dll
30.04.2023  22:04            44.440 dxdllreg_x86.cab
30.04.2023  22:04        13.264.168 dxnt.cab
30.04.2023  22:04           525.656 DXSETUP.exe
30.04.2023  22:04            95.637 dxupdate.cab
30.04.2023  22:04         1.013.225 Feb2005_d3dx9_24_x86.cab
30.04.2023  22:04         1.084.712 Feb2006_d3dx9_29_x86.cab
30.04.2023  22:04           132.409 Feb2006_XACT_x86.cab
30.04.2023  22:04           147.983 FEB2007_XACT_x86.cab
30.04.2023  22:04         1.064.925 Jun2005_d3dx9_26_x86.cab
30.04.2023  22:04           133.663 JUN2006_XACT_x86.cab
30.04.2023  22:04           698.464 JUN2007_d3dx10_34_x86.cab
30.04.2023  22:04         1.607.278 JUN2007_d3dx9_34_x86.cab
30.04.2023  22:04           152.901 JUN2007_XACT_x86.cab
30.04.2023  22:04           849.919 JUN2008_d3dx10_38_x86.cab
30.04.2023  22:04         1.463.878 JUN2008_d3dx9_38_x86.cab
30.04.2023  22:04            21.905 JUN2008_X3DAudio_x86.cab
30.04.2023  22:04            93.128 JUN2008_XACT_x86.cab
30.04.2023  22:04           269.016 JUN2008_XAudio_x86.cab
30.04.2023  22:04           818.260 Mar2008_d3dx10_37_x86.cab
30.04.2023  22:04         1.443.274 Mar2008_d3dx9_37_x86.cab
30.04.2023  22:04            21.867 Mar2008_X3DAudio_x86.cab
30.04.2023  22:04            93.726 Mar2008_XACT_x86.cab
30.04.2023  22:04           226.242 Mar2008_XAudio_x86.cab
30.04.2023  22:04         1.040.737 Mar2009_d3dx10_41_x86.cab
30.04.2023  22:04         1.612.446 Mar2009_d3dx9_41_x86.cab
30.04.2023  22:04            21.298 Mar2009_X3DAudio_x86.cab
30.04.2023  22:04            92.732 Mar2009_XACT_x86.cab
30.04.2023  22:04           273.010 Mar2009_XAudio_x86.cab
30.04.2023  22:04           803.876 Nov2007_d3dx10_36_x86.cab
30.04.2023  22:04         1.709.360 Nov2007_d3dx9_36_x86.cab
30.04.2023  22:04            18.496 NOV2007_X3DAudio_x86.cab
30.04.2023  22:04           148.264 NOV2007_XACT_x86.cab
30.04.2023  22:04           965.421 Nov2008_d3dx10_40_x86.cab
30.04.2023  22:04         1.550.796 Nov2008_d3dx9_40_x86.cab
30.04.2023  22:04            21.843 Nov2008_X3DAudio_x86.cab
30.04.2023  22:04            92.676 Nov2008_XACT_x86.cab
30.04.2023  22:04           272.603 Nov2008_XAudio_x86.cab
30.04.2023  22:04            45.351 Oct2005_xinput_x86.cab
30.04.2023  22:04         1.127.209 OCT2006_d3dx9_31_x86.cab
30.04.2023  22:04           138.009 OCT2006_XACT_x86.cab
              75 Datei(en),     64.275.282 Bytes

 Verzeichnis von D:\SteamLibrary\steamapps\common\Septerra Core\qt

30.04.2023  22:05    <DIR>          .
30.04.2023  22:05    <DIR>          ..
30.04.2023  22:04            50.525 QuickTime.qtp
30.04.2023  22:04         3.793.920 QuickTime.qts
30.04.2023  22:04               589 QuickTimeInstaller.bat
30.04.2023  22:04        41.404.760 QuickTimeInstaller.exe
30.04.2023  22:04               503 QuickTimeUninstall.bat
               5 Datei(en),     45.250.297 Bytes

 Verzeichnis von D:\SteamLibrary\steamapps\common\Septerra Core\savedata

30.04.2023  22:08    <DIR>          .
30.04.2023  22:08    <DIR>          ..
30.04.2023  14:16           219.264 !QuickSave.scg
30.04.2023  14:16           219.264 1.scg
30.04.2023  22:08                51 steam_autocloud.vdf
               3 Datei(en),        438.579 Bytes

     Anzahl der angezeigten Dateien:
             128 Datei(en),    852.375.295 Bytes
              11 Verzeichnis(se), 854.704.734.208 Bytes frei
`

**Comment by M-HT** [comment]
I only had english version of Septerra Core, but I found a patch to german version. The file sizes match yours, but I'm not having any problems with it.

You wrote that there's a black screen for a few seconds, are you playing it in fullscreen ? Did you also tried playing in window ?

**Comment by mitharas** [comment]
> You wrote that there's a black screen for a few seconds, are you playing it in fullscreen ? Did you also tried playing in window ?  
  
Yep, I tried a few different settings, including the defaults (640*480 windowed). In that case there is no blackscreen, the window closed as soon as the intro movies are finished.

**Comment by M-HT** [comment]
Can you post the content of the file `septerra.mft` for comparison? This is mine:
```
Terrabuilder version 1.0000 LV25 AM04 GV00 TX00 CH14 IL00 
[LOCAL]\septerra.idx
[LOCAL]\sound.db
[LOCAL]\anim.db
[LOCAL]\level.db
[LOCAL]\text.db
[LOCAL]\septerra.db
[LOCAL]\valkyrie.db
[LOCAL]\m2.db
[LOCAL]\m3.db
[LOCAL]\m4.db
[LOCAL]\m5.db
[LOCAL]\m6.db
[LOCAL]\m7.db
[LOCAL]\m8.db
[LOCAL]\monolith.db
[LOCAL]\topware.db
[LOCAL]\m1.db
[LOCAL]\m9a.db
[LOCAL]\m9b.db
```

Try creating a batch file (e.g. test.bat) in the game's directory with these lines and running it (audio should be disabled). Does the game still crash ?
```
set SDL_AUDIODRIVER=dummy
SR-Septerra.exe
```

If it still crashes, try disabling intro in Septerra.cfg and put these lines in the batch file and run it (video should be disabled). Does the game crash or can you hear the audio ?
```
set SDL_VIDEODRIVER=dummy
SR-Septerra.exe
```

**Comment by mitharas** [comment]
I tried 
> set SDL_AUDIODRIVER=dummy  
   
This didn't work, same behaviour as before (sans sound).  
  
> set SDL_VIDEODRIVER=dummy  
  
This resulted in nothing really happening.
![grafik](https://user-images.githubusercontent.com/8302737/235740510-e1331e9c-d7c1-48e5-b5d2-3dd3d18d2d6f.png)

If I look at the task manager while launching the .bat, I can see SR-Septerra.exe existing for a few seconds and disappearing again.  
  
> Can you post the content of the file septerra.mft for comparison? This is mine:  
  
Mine looks absolutely identical. 
```
Terrabuilder version 1.0000 LV25 AM04 GV00 TX00 CH14 IL00 
[LOCAL]\septerra.idx
[LOCAL]\sound.db
[LOCAL]\anim.db
[LOCAL]\level.db
[LOCAL]\text.db
[LOCAL]\septerra.db
[LOCAL]\valkyrie.db
[LOCAL]\m2.db
[LOCAL]\m3.db
[LOCAL]\m4.db
[LOCAL]\m5.db
[LOCAL]\m6.db
[LOCAL]\m7.db
[LOCAL]\m8.db
[LOCAL]\monolith.db
[LOCAL]\topware.db
[LOCAL]\m1.db
[LOCAL]\m9a.db
[LOCAL]\m9b.db
```

**Comment by mitharas** [comment]
I got a solution: I changed the language in steam to english and it worked. That's not a big deal, my english is good enough. I just liked the german voice of the main character a lot.  
  
Thank you very much for your help though, that level of support is not natural for a fan project regardomg a decades old game.
