### ISSUE TITLE
Albion: 3D mode is too dark

### ISSUE THREAD

**Issue by neuromancer** [M-HT/SR#6]
This was tested during the first time you enter in 3D mode:

![dark](https://user-images.githubusercontent.com/110782/77255309-32db5680-6c45-11ea-90d2-a991768c981a.png)

**Comment by M-HT** [comment]
It's too dark, because it's night. There's enough light during the day. I recommend that you find and activate the clock, so you'll know what time it is.

**Comment by neuromancer** [comment]
Oh, right. I checked some Albion screenshots and I did not see examples of night time. Thanks for the clarification! Btw, if there is no planned feature to add brightness (or something like that), feel free to close this issue.

**Comment by M-HT** [comment]
I think that Albion is bright enough, so I'm closing this issue.
