### ISSUE TITLE
Albion (GNU/Linux 64bit): Crash to desktop entering battle and no midi-output

### ISSUE THREAD

**Issue by throgh** [M-HT/SR#60]
Hello,

I have tested now running Albion on GNU/Linux 64bit: When entering a battle, the game is crashing.
Last error-message:

`
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  4 (X_DestroyWindow)
  Resource id in failed request:  0x400017
  Serial number of failed request:  180
  Current serial number in output stream:  183
`

Furthermore I have tried different midi-options, including bassmidi, and got no current output.

**Comment by M-HT** [comment]
> I have tested now running Albion on GNU/Linux 64bit: When entering a battle, the game is crashing. Last error-message:

Are you using the SDL1 or SDL2 version ? If you're using SDL1 version can you try the SDL2 version ?
Can you post a save file before combat, so I can test it (because it's not crashing for me) ?

> Furthermore I have tried different midi-options, including bassmidi, and got no current output.

First, let's try midi output using libADLMIDI:
In file Albion.cfg, Audio_MIDI_Subsystem should be set to adlmidi (`Audio_MIDI_Subsystem=adlmidi`).
In the game directory, you should have a file `midi-adlmidi.so`.
You should have a file `libADLMIDI.so.1` either in the game directory or it should be installed, so it can be found by the dynamic linker.

Can you run the command ```LD_LIBRARY_PATH=`pwd` ldd midi-adlmidi.so``` in the game directory and post the result ?

**Comment by throgh** [comment]
Hello,

thanks for the ideas and replying.
First coming to the midi-output with libadlmidi. I have build a package for the system so it is native available. Here the output from the terminal:

`
	linux-vdso.so.1 (0x00007ffc2bf0c000)
	libADLMIDI.so.1 => /usr/lib/libADLMIDI.so.1 (0x00007f6db843e000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f6db82b4000)
	libc.so.6 => /lib/libc.so.6 (0x00007f6db80f0000)
	libm.so.6 => /lib/libm.so.6 (0x00007f6db7faa000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f6db7f90000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6db84ea000)
`

Furthermore I have tried and build SR-Main with SDL2-support. When entering battle the game is now just crashing with a segmentation-fault. Attached you can find the savegame I have created earlier.

[Download](https://files.catbox.moe/kwyq9f.gz)

(Sorry, did not find another possible on the run for now to get the tarball to you!)

**Comment by M-HT** [comment]
I fixed a bug in the 64-bit version. That should solve the issue with game crashing when entering battle.

I'm not seeing any problem with midi playing, so just to check, in the options (in the game) do you have the music volume set high enough ?

**Comment by throgh** [comment]
Hello, thanks for fixing the crash. So far that is working. Onwards for the midi-playback: I have tried now so far all different ways and get no output. I have now tried to connect through alsa direct and can playback midi as always through for example Timidity. Here the output:

`
client 14: 'Midi Through' [type=Kernel]
    0 'Midi Through Port-0'
client 128: 'TiMidity' [type=User,pid=2500]
    0 'TiMidity port 0 '
    1 'TiMidity port 1 '
    2 'TiMidity port 2 '
    3 'TiMidity port 3 
`

Should I use a different notation for alsa instead the port?
The volume is highest possible set in Albion itself. The library for alsa is also there. But within the game I have no music-playback.

**Comment by throgh** [comment]
Have tried, but also no further music-output. Also I have tried running even wildmidi and adlmidi side by side running: Midi-output is there, but not throughout the game itself.

**Comment by M-HT** [comment]
I added a code to show information about loaded plugins, but I think I know what's the problem.
I forgot that in Albion you also need `midiA-wildmidi.so` and `libWildMidiA.so.1`, otherwise midi output won't work.

**Comment by M-HT** [comment]
I fixed more bugs and I also uploaded a compiled version to the releases.
