### ISSUE TITLE
SepterraCore, issue with the mouse cursor when resolution is changed

### ISSUE THREAD

**Issue by Kryloiw** [M-HT/SR#62]
SepterraCore-Windows-x86-v1.04.0.9 and v1.04.0.8

After changing the resolution to 1400x1080 (100% repo rate in fullscreen) in the Septerra.cfs, the mouse cursor gets stuck in the top left corner of the store screen.

Issue does not occur in v1.04.0.7

![image](https://github.com/M-HT/SR/assets/33604327/5b3dad60-2c9c-4372-98c9-092e1517aa59)

**Comment by M-HT** [comment]
I created a new release with the fix.

**Comment by Kryloiw** [comment]
Thank you; fix confirmed :)
