### ISSUE TITLE
Septerra Core battle speed enhancement

### ISSUE THREAD

**Issue by NineKain** [M-HT/SR#64]
Any chance of a way to increase/double battle speed? even game speed in general, im liking the game but damn is it slow

**Comment by M-HT** [comment]
Sorry, I don't know of any way to do that.

You can save some time by changing the default movement speed from walk to run - in file `Septerra.cfg` change `Option_DefaultMovement=walk` to `Option_DefaultMovement=run`

**Comment by NineKain** [comment]
Yeah I have that enabled, I meant general game speed/battle speed, like run the game/battles at 2x speed or something, like a fast forward
