### ISSUE TITLE
Albion (linux-x86-v1.7.4-sdl2) freezes when switching desktops.

### ISSUE THREAD

**Issue by RobertZenz** [M-HT/SR#65]
The game freezes (no matter in what state it is) when one does switch between different desktops (`Ctrl+Alt+Left/Right`). Changing to another window (`Alt+Tab`) works fine, though.

This is on a system with Xorg+MATE+Sawfish, if that matters. I wouldn't exclude that it might be related to my system, do you have an idea what that might be?

**Comment by M-HT** [comment]
I don't know what might be the problem. What distribution are you using ?

I tried Linux Mint with MATE and it worked there. I installed Sawfish, but when I try to use it I only get an error and black screen, so I can't try Albion there.

**Comment by RobertZenz** [comment]
Ubuntu, a quite old one to be honest, so that might be the problem. Though, I haven't observed this with any other game or application so far. Sorry, it's rather late, if you've got an idea how I could debug that I'll give it a try.

**Comment by M-HT** [comment]
An which version of Ubuntu ?

**Comment by RobertZenz** [comment]
That would be 16.04 (under ESM) with SDL2 2.0.10.

I would not exclude that that is the problem.

**Comment by M-HT** [comment]
I can't get Sawfish working in Ubuntu 16.04, but Albion doesn't freeze when switching desktops in MATE with SDL 2.0.4 which is default in Ubuntu 16.04.

Can you test it in MATE and/or with SDL 2.0.4 ?

Alternatively you can try using linux-x86-v1.7.4-sdl1.

**Comment by RobertZenz** [comment]
The SDL1 version also freezes when switching between desktops (everything else is working fine). I can also produce this with the default MATE window manager Marco running.

If you can't reproduce it, I'd assume it is something in my environment only...which might very well be.

Thanks for looking into it anyway, and thank you very much for this project. Playing the 3D parts at native resolution looks so good!
