### ISSUE TITLE
Unable to compile - Judy unresolved external symbols

### ISSUE THREAD

**Issue by enderdrag64** [M-HT/SR#66]
I've spent most of my day today trying to compile this and failing. I'm using windows 10, visual studio 2022. It doesn't matter whether I use scons or not, the end result is the same - it compiles fine, but the visual studio linker is unable to find any of the symbols in judy.lib

I've attached the errors, as well as the output of running dumpbin on the lib file. Clearly the symbols are there, I'm really not sure what the problem is.

![unresolved_symbols](https://github.com/M-HT/SR/assets/33301226/931cf8a0-3503-4e54-952c-be58e4a5eabb)
[symbols.txt](https://github.com/M-HT/SR/files/15382872/symbols.txt)

**Comment by M-HT** [comment]
I don't have visual studio 2022, I'm testing it on older version where link still supports option /LIB, but that's just a minor issue.
My generated .lib file is also small (11 kB), but has the exported symbols:
<details>
<summary>dumpbin /exports judy.lib</summary>

```
Microsoft (R) COFF/PE Dumper Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file judy.lib

File Type: LIBRARY

     Exports

       ordinal    name

                  _Judy1ByCount
                  _Judy1Count
                  _Judy1First
                  _Judy1FirstEmpty
                  _Judy1FreeArray
                  _Judy1Last
                  _Judy1LastEmpty
                  _Judy1MallocSizes
                  _Judy1MemActive
                  _Judy1MemUsed
                  _Judy1Next
                  _Judy1NextEmpty
                  _Judy1Prev
                  _Judy1PrevEmpty
                  _Judy1Set
                  _Judy1SetArray
                  _Judy1Test
                  _Judy1Unset
                  _JudyFree
                  _JudyHSDel
                  _JudyHSFreeArray
                  _JudyHSGet
                  _JudyHSIns
                  _JudyLByCount
                  _JudyLCount
                  _JudyLDel
                  _JudyLFirst
                  _JudyLFirstEmpty
                  _JudyLFreeArray
                  _JudyLGet
                  _JudyLIns
                  _JudyLInsArray
                  _JudyLLast
                  _JudyLLastEmpty
                  _JudyLMallocSizes
                  _JudyLMemActive
                  _JudyLMemUsed
                  _JudyLNext
                  _JudyLNextEmpty
                  _JudyLPrev
                  _JudyLPrevEmpty
                  _JudyMalloc
                  _JudyMallocVirtual
                  _JudySLDel
                  _JudySLFirst
                  _JudySLFreeArray
                  _JudySLGet
                  _JudySLIns
                  _JudySLLast
                  _JudySLNext
                  _JudySLPrev

  Summary

          BA .debug$S
          14 .idata$2
          14 .idata$3
           4 .idata$4
           4 .idata$5
           A .idata$6
```
</details>

What's your output of `dumpbin /exports judy.lib` ?

**Comment by enderdrag64** [comment]
It looks like this: 
`Microsoft (R) COFF/PE Dumper Version 14.39.33523.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file Judy.lib

File Type: LIBRARY

COFF SYMBOL TABLE
000 010175CA ABS    notype       Static       | @comp.id
001 00000000 SECT2  notype       External     | __IMPORT_DESCRIPTOR_judy
002 C0000040 SECT2  notype       Section      | .idata$2
003 00000000 SECT3  notype       Static       | .idata$6
004 C0000040 UNDEF  notype       Section      | .idata$4
005 C0000040 UNDEF  notype       Section      | .idata$5
006 00000000 UNDEF  notype       External     | __NULL_IMPORT_DESCRIPTOR
007 00000000 UNDEF  notype       External     | judy_NULL_THUNK_DATA

String Table Size = 0x4C bytes

COFF SYMBOL TABLE
000 010175CA ABS    notype       Static       | @comp.id
001 00000000 SECT2  notype       External     | __NULL_IMPORT_DESCRIPTOR

String Table Size = 0x1D bytes

COFF SYMBOL TABLE
000 010175CA ABS    notype       Static       | @comp.id
001 00000000 SECT2  notype       External     | judy_NULL_THUNK_DATA

String Table Size = 0x1A bytes

  Summary

          BA .debug$S
          14 .idata$2
          14 .idata$3
           4 .idata$4
           4 .idata$5
           A .idata$6
`

**Comment by M-HT** [comment]
That looks like the output of `dumpbin /symbols judy.lib`. Can you check the output of `dumpbin /exports judy.lib` ?

**Comment by enderdrag64** [comment]
Ahh good catch. With /exports it looks the same as yours. I still get unresolved external symbols when trying to link with it though

**Comment by enderdrag64** [comment]
> I'm not sure I can help you any further. I made a test program and it linked with judy.lib without any problems.

May I ask what version of Visual Studio you're using? I may just restart with that

**Comment by M-HT** [comment]
May I ask what you are trying to achieve ?
I'm not sure this project works with compilers other than gcc/clang.
And if you can't compile it, are you sure you have the skills/knowledge to do something with it ?

**Comment by enderdrag64** [comment]
> I'm not sure this project works with compilers other than gcc/clang.
Then why is your SConstruct script built to use Visual Studio?

**Comment by M-HT** [comment]
That's how `scons` works. I didn't do anything specific for Visual Studio.
I'm not stopping you from using Visual studio, but i don't use it so don't expect much help.

**Comment by enderdrag64** [comment]
Okay so I switched to gcc inside msys2 and I tried building (gcc *.c -lJudy -ludis86) and I'm still getting undefined references involving Judy, even after rebuilding it from scratch with gcc too.

![image](https://github.com/M-HT/SR/assets/33301226/38991bbd-db07-4cef-b9ea-797ec880c6cd)

**Comment by enderdrag64** [comment]
I finally managed to build SR successfully!

Using the official judy 1.05 release from SourceForge like I had been was a lost cause, but I found this fork over at https://github.com/dlmiles/libjudy that has fixes specifically to fix compatibility with msys. After building and installing that version I was able to link against it successfully.

I'd recommend updating your documentation to clarify that you should compile with msys/gcc instead of scons/visual studio, and perhaps link to the working judy fork

**Comment by M-HT** [comment]
Using Judy library is now optional and the project should work with Visual Studio.
