### ISSUE TITLE
Septerra Core - Semi-locking after battle

### ISSUE THREAD

**Issue by tkeggarr** [M-HT/SR#69]
Hello! Thanks much for all of your effort in bringing this brilliant classic back to life.

Using your latest patch on GoG install everything is working well apart from game sort of freezes after battle. I have to hold WASD directional key until the camera moves back to the characters and then it will resolve. Until I do that it will act like its still in battle. Like I can select a character and their menu comes up and I can assign cards to characters and whatnot, they just won't take any actual actions.

EX:
https://www.youtube.com/watch?v=t47gx68Uzhw

**Comment by M-HT** [comment]
I never experienced something like that. Does it happen in every battle (on every map) ?
What operating system are you using ?
What configuration are you using (what's the content of the file Septerra.cfg) ?

**Comment by tkeggarr** [comment]
Ugh false alarm I think. I had originally bought this on Steam but it was pretty rough. Tried it on GoG with your patch which was golden. Apparently I've been going back into the steam folder by habit and launching SR-Septerra from there on the borked install. GoG install is still working as expected. Sorry for wasting your time. Thanks again for all your work on this.

**Comment by KG-Heinze** [comment]
Hello, i have the same Issue and i didn't install it with Steam ^^"

My Steps:
1. Fresh install from GoG. 
2. Downloaded [SepterraCore-Windows-x86-v1.04.0.12.zip]
3. Put all files into GOG Galaxy\Games\Septerra Core
4. Started SR-Septerra

My Operating System: Windows 10 Home 

Only started the game, so can't tell if it gets better later on.

**Content of my File:** 

Game_Installation=portable

Intro_Play=no

Display_Mode=window
Display_VSync=off
Display_Width=640
Display_Height=480
Display_Resizable=yes
Display_Scaling=basic
Display_IntegerScaling=no
Display_DelayAfterFlip=0

Audio_SampleRate=0
Audio_BufferSize=0
Audio_ResamplingQuality=1

Patch_PreselectCharacters=yes

Option_DefaultMovement=run
Option_MovieResolution=doubled
Option_MoviesPlay=yes
Option_PointSoundsPlay=yes
Option_SoundsPlay=yes

Cheat_ENEMIES=disabled
Cheat_SIGHT=disabled
Cheat_HIDETEXT=disabled
Cheat_FPS=disabled

Input_GameController=no
Controller_Deadzone=1000

Keys_WSAD=WSAD
Keys_ArrowKeys=ArrowKeys

CPU_SleepMode=standard



Example: 
https://streamable.com/ppyxkv

**Comment by M-HT** [comment]
I turned on Vsync in the configuration files in the release. That will hopefully prevent this issue from occuring in the future.
