### ISSUE TITLE
Septerra Core: Audio values are not saved

### ISSUE THREAD

**Issue by dukemagus** [M-HT/SR#72]
How to reproduce the issue:
- Start the game
- Change the audio settings (volume)
- Save the game
- Close and reopen the game
- Continue

The volume sliders will all return to default (maximum) value

**Comment by M-HT** [comment]
I'm guessing you're using Windows 10 (or anything higher than Windows XP).
The issue is with permissions for writing to registry.
A workaround will be available in the next release.

**Comment by M-HT** [comment]
I created a [new release](https://github.com/M-HT/SR/releases/tag/septerra_v1.04.0.12).
It contains a new option in the configuration file `Septerra.cfg`:
`Game_Installation=installed/portable`
If the value is `portable` then the game won't use Windows registry and will store game settings in a file.
Previous releases worked like the value was `installed`.

**Comment by dukemagus** [comment]
Issue fixed. Thank you.
