### ISSUE TITLE
Albion: time going too fast

### ISSUE THREAD

**Issue by kimujifour** [M-HT/SR#73]
It might be an issue induced by the previous 1.7.2 update that brought the screen redraw rate to 60. The time is passing much faster than it should. I've compared how fast minutes passes on the in game clock to regular dosbox versions of the game and it seems to be going at least twice as fast. As a result you get the boarding call way sooner in the intro and it repeats very quickly when you dismiss it, the party has to rest much more often, days are going way faster, etc.

I'm not sure if other aspects of the game are affected, like characters moving too fast or if the music playing at the normal speed.

 Using Albion-Linux-x86-v1.8.0-sdl2.tar.gz on Mint LMDE with the  GOG version of the game.

**Comment by M-HT** [comment]
The problem seems to be, that the game speed in DOSBox depends on cycles setting (maybe also other settings).
I tested it (later in the game, after you find a clock) with following results:
* when using my executable, one in-game hour takes about 64 seconds
* in DOSBox with 65000 or higher cycles, one in-game hour also takes about 64 seconds
* in DOSBox with 60000 cycles, one in-game hour takes about 85 seconds
* in DOSBox with 20000 cycles, one in-game hour takes about 102 seconds

Please test it yourself, but at the moment I don't consider this a bug.

**Comment by kimujifour** [comment]
Well I don't know what's wrong on my end then, because one in-game hour takes only 20 seconds. I'm playing on a old laptop that isn't fast at all (an old ivy bridge i5).

Here's my albion.cfg:
> Intro=on
> 
> Sound=on
> Music=on
> 
> Audio_Channels=stereo
> Audio_Resolution=16
> Audio_Sample_Rate=48000
> Audio_Buffer_Size=4096
> Audio_Resampling_Quality=1
> Audio_Swap_Channels=yes
> Audio_MIDI_Subsystem=bassmidi
> Audio_SoundFont_Path=/usr/share/sounds/sf2/FluidR3_GM.sf2
> Audio_MIDI_Device=
> Audio_OPL3_Emulator=precise
> 
> Display_ScaledWidth=720
> Display_ScaledHeight=480
> Display_Fullscreen=no
> Display_Enhanced_3D_Rendering=on
> Display_MouseCursor=minimal
> Display_Scaling=basic
> Display_AdvancedScaler=normal
> Display_ScalerFactor=max
> Display_ExtraScalerThreads=auto
> 
> Screenshot_Format=Original
> Screenshot_Enhanced_Resolution=off
> Screenshot_Enabled=no
> Screenshot_Automatic_Filename=no
> 
> Input_GameController=yes
> Controller_Deadzone=1500
> 
> Keys_WSAD=WSAD
> Keys_ArrowKeys=ArrowKeys

And the content of setup.ini:

> 
> [SYSTEM]
> VESA=Y
> FPU=Y
> SOURCE_PATH=ALBIONCD\
> LANGUAGE=2
> [VESA]
> MODE_1024x768x16.2M=y
> MODE_800x600x16.2M=Y
> MODE_640x480x16.2M=Y
> MODE_1024x768x64k=Y
> MODE_800x600x64k=Y
> MODE_640x480x64k=Y
> MODE_1024x768x32k=Y
> MODE_800x600x32k=Y
> MODE_640x480x32k=Y
> MODE_1024x768x256=Y
> MODE_800x600x256=Y
> MODE_640x480x256=Y
> MODE_640x400x256=Y
> MEMORY=2097152
> VESA_VERSION_SUBNUMBER=0
> VESA_VERSION_NUMBER=2
> OEM=S3
> [ALBION]
> SAVED_GAME_NR=100
> MIDI_VOLUME=100
> DIGI_VOLUME=70
> 3D_WINDOW_SIZE=100
> COMBAT_DETAIL_LEVEL=5
> COMBAT_MESSAGE_SPEED=10

**Comment by M-HT** [comment]
I was measuring the time in the city (in 3D view). Inside (in 2D view), the clock is running faster (one in-game hour takes about 20 seconds), but it's the same speed when using DOSBox (unless the cycles are low).

**Comment by kimujifour** [comment]
Alright I'm getting exactly the same as you. I was measuring in top down 2D view. I just tried in the 3D sections and I'm getting 64 seconds. So it appears to be normal, the youtube vids I was using as reference were showing 3D sections and I was comparing with my 2D interiors results. it's just that there's a massive difference between 2D and 3D. So it's simply how the game works. I wish the original devs had thought of a time scale slider in the option so we could adjust it, the inside the clock runs a bit too fast imo.

So, the "issue" is solved as far as SR is concerned.
