### ISSUE TITLE
Feature Request: Septerra Core show enemies hit points on start

### ISSUE THREAD

**Issue by TaxAkla** [M-HT/SR#9]
Vanilla Septerra has a cheat code that shows enemies hit points. Can SR have an option on CFG that enables that feature on start?

https://www.cheatcc.com/pc/septerracore.html

**Comment by M-HT** [comment]
I'll take a look at it and other cheats.

**Comment by Juli199696** [comment]
@M-HT  You sir are a legend. Please make it portable to ARM devices <3

**Comment by M-HT** [comment]
Septerra Core release version 1.04.0.5 contains options to enable cheat codes.

**Comment by TaxAkla** [comment]
Thank  you
